CREATE TABLE commande (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    prix_final NUMERIC(10, 2) NOT NULL CHECK (prix_final >= 0),
    reduction_appliquee BOOLEAN NOT NULL DEFAULT FALSE,
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
